### ISSUE TITLE
Why that name?

### ISSUE THREAD

**Issue by bobybobybob** [agnunez/ESP8266-I2C-LCD1602#1]
Why is the same name used as the LCD i2c library for ordinary Arduino boards use? So that users are confused and can not use both the one für ESO8266 and the other für Real Arduinos? Is it so hard to put behind the library name its own string so that there are no problems with different versions for other platforms? Exampel: LiquidCrystal_I2C_ESP8266.h than LiquidCrystal_I2C.h   or much better LiquidCrystal_I2C_ESP8266_agn.h  that show it is the esp version from agnunez.

**Comment by agnunez** [comment]
Ask  https://github.com/fdebrabander/  He was the one that re-used the name. I just added a functionality to  allow SDA SCL line to be configurable from its call.
Anyway, ideally the generic name should be work independently of the MCU were Arduino UNO, Mega, ESP8266 etc.. to allow the code to be portable. So this configuration should be detected by #DEFINEs at compiling time and became transparent for the programmer. Just my thoughts!
